
Parameters:
  KeyName:
    Type: String
    Description: nome ssh key
  YourName:
    Type: String
    Description: Damiano
  YourSurname:
    Type: String
    Description: Caratelli

  VPCCIDR:
    Description: Blocco CIDR per la VPC (es. 10.0.0.0/16)
    Type: String
    Default: 10.0.0.0/16



  


